DELTA_T = 0.002

X=0; Y=1; Z=2
CEILING = 1.
TURN_FACTOR = 1.5
TURN_MARGIN = 0.1

# Combat
FIRING_RANGE = 0.1
CYLINDER_RADIUS = 0.01

# Sensors
COMM_RANGE_MAX = 0.6 # Can see everything from center
COMM_RANGE_MIN = 0.15

VIZ_RANGE_MAX = 0.5 # Can see almost everything from center
VIZ_RANGE_MIN = 0.15

# Flight
MAX_SPEED = 6
MIN_SPEED = 2
MAX_TURN_FORCE = 0.1
COLLISION_DIST = 0.01

# Obstacles
OBSTACLE_RADIUS = 0.05
AVOID_MARGIN_XY = 0.10
AVOID_MARGIN_Z = 0.05